name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test building process'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Go Mod
        run: go mod download && go mod vendor

      - name: Make Binaries amd64
        run: make binary-linux-amd64
      
      - name: Make Binaries aarch64
        run: make binary-linux-arm64

      - name: Change Permissions
        run: chmod +x ./bin/linux/amd64/local-persist

      - name: Start in the Background
        run: sudo ./bin/linux/amd64/local-persist &

      - name: Integration Tests
        run: ./scripts/integration.sh

      - name: Unit Tests
        run: make test
